name: CI

on:
  pull_request:
    branches: [ main ]

env:
  NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL
  TOKEN_URL: $TOKEN_URL
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  GRANT_TYPE: 'password'

jobs:

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Playwright Browsers
      run: npm exec playwright install --with-deps
    - name: Install build dependecies
      run: yarn global add pnpm
    - name: Install App Dependencies
      run: pnpm install
    - name: Build source
      run: pnpm run build
    - name: Run Playwright tests
      run:  pnpm run test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30


  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Build Dependencies
      run : yarn global add pm2; yarn global add pnpm
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master  
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_KEY }}
        script: |
          set -e
          cd /var/www/kmhflv3
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          if ! [[ -d './.git' ]]; then git init; fi
          if ! [[ `git remote -v | awk '{print $1}' | head -n 1` =~ 'origin' ]]; then git remote add origin ${{ github.server_url }}${{ github.username }}/${{ github.repository }}.git; fi
          git pull origin main
          pnpm install
          pnpm run build
          npx pm2 restart all
          
          
  

