name: Deploy to kmhfl server

on:
  push:
    branches:
      - master

env:
  GIT_REPO: $GIT_REPO
  NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL
  TOKEN_URL: $TOKEN_URL
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Build dependencies
      run: yarn global add next

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_KEY }}
        script: |
          set -e
          cd /var/www/kmhflv3
          sudo touch .env
          cat > .env << EOF 
              CLIENT_ID=$CLIENT_ID
              CLIENT_SECRET=$CLIENT_SECRET
              CLIENT_TYPE='confidential'
              GRANT_TYPE='password'
              TOKEN_URL=$TOKEN_URL
              NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
          EOF
          if ! [[ -d './.git' ]]; then git init; fi
          git remote add origin $GIT_REPO
          git pull origin master
          yarn 
          yarn run build
          yarn run start
  

